export const CONSTANT = {
  STATUS_SUMMARY_AVAILABLE: "Available",
  STATUS_SUMMARY_BUSY: "Busy",
  STATUS_SUMMARY_AT_WORK: "At Work",
  STATUS_SUMMARY_SLEEPING: "Sleeping",
  STATUS_SUMMARY_AT_GYM: "At Gym",

  STATUS_MESSAGE_DELIVERED: "delivered",
  STATUS_MESSAGE_NOT_DELIVERED: "not delivered",
  STATUS_MESSAGE_SENT: "sent",
  STATUS_MESSAGE_READ: "read",
  STATUS_MESSAGE_UNREAD: "unread",
};