import { CONSTANT } from "./CONSTANTS.ts";

export const DUMMY_DATA = {
  app: "WhatsApp",
  version: "2.22.10.72",
  users: [
    {
      userId: "6",
      name: "Diana Evans",
      phoneNumber: "+1122334455",
      profilePic: "https://i.pravatar.cc/150?img=6",
      status: "On vacation",
      messages: [
        {
          messageId: "msg-31",
          message: "How's the vacation going?",
          sentDate: "2023-10-06T10:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-32",
          message: "It's amazing!",
          sentDate: "2023-10-06T10:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-33",
          message: "That's great to hear!",
          sentDate: "2023-10-06T10:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-34",
          message: "Thanks!",
          sentDate: "2023-10-06T10:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-35",
          message: "Send some pictures!",
          sentDate: "2023-10-06T10:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-36",
          message: "Sure, will do.",
          sentDate: "2023-10-06T10:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    // User 7
    {
      userId: "7",
      name: "Eva Green",
      phoneNumber: "+6677889900",
      profilePic: "https://i.pravatar.cc/150?img=7",
      status: "Available",
      messages: [
        {
          messageId: "msg-37",
          message: "Hey, are you free for a call?",
          sentDate: "2023-10-07T15:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-38",
          message: "Yes, call me now.",
          sentDate: "2023-10-07T15:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-39",
          message: "Calling you now.",
          sentDate: "2023-10-07T15:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-40",
          message: "Okay.",
          sentDate: "2023-10-07T15:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-41",
          message: "Did you get the file I sent?",
          sentDate: "2023-10-07T15:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-42",
          message: "Not yet.",
          sentDate: "2023-10-07T15:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    // User 8
    {
      userId: "8",
      name: "Frank Harris",
      phoneNumber: "+3344556677",
      profilePic: "https://i.pravatar.cc/150?img=8",
      status: "In a meeting",
      messages: [
        {
          messageId: "msg-43",
          message: "Can we reschedule the meeting?",
          sentDate: "2023-10-08T09:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-44",
          message: "Yes, let's move it to tomorrow.",
          sentDate: "2023-10-08T09:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-45",
          message: "Sounds good. What time?",
          sentDate: "2023-10-08T09:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-46",
          message: "10 AM works for me.",
          sentDate: "2023-10-08T09:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-47",
          message: "Perfect, see you then.",
          sentDate: "2023-10-08T09:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-48",
          message: "👍",
          sentDate: "2023-10-08T09:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    // User 9
    {
      userId: "9",
      name: "Grace Lee",
      phoneNumber: "+7788990011",
      profilePic: "https://i.pravatar.cc/150?img=9",
      status: "Studying",
      messages: [
        {
          messageId: "msg-49",
          message: "Hey, how's the studying going?",
          sentDate: "2023-10-09T20:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-50",
          message: "It's going well, just a lot to cover.",
          sentDate: "2023-10-09T20:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-51",
          message: "You got this!",
          sentDate: "2023-10-09T20:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-52",
          message: "Thanks!",
          sentDate: "2023-10-09T20:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-53",
          message: "Let me know if you need help.",
          sentDate: "2023-10-09T20:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-54",
          message: "Will do!",
          sentDate: "2023-10-09T20:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    // User 10
    {
      userId: "10",
      name: "Henry Wilson",
      phoneNumber: "+9900112233",
      profilePic: "https://i.pravatar.cc/150?img=10",
      status: "Gaming",
      messages: [
        {
          messageId: "msg-55",
          message: "Hey, want to play a game?",
          sentDate: "2023-10-10T18:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-56",
          message: "Sure, what are we playing?",
          sentDate: "2023-10-10T18:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-57",
          message: "How about some COD?",
          sentDate: "2023-10-10T18:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-58",
          message: "Let's do it!",
          sentDate: "2023-10-10T18:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-59",
          message: "I'll invite you to the lobby.",
          sentDate: "2023-10-10T18:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-60",
          message: "Okay, waiting.",
          sentDate: "2023-10-10T18:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    // User 11
    {
      userId: "11",
      name: "Ivy Moore",
      phoneNumber: "+4455667788",
      profilePic: "https://i.pravatar.cc/150?img=11",
      status: "Cooking",
      messages: [
        {
          messageId: "msg-61",
          message: "What are you cooking?",
          sentDate: "2023-10-11T19:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-62",
          message: "Pasta!",
          sentDate: "2023-10-11T19:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-63",
          message: "Yum! Can I come over?",
          sentDate: "2023-10-11T19:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-64",
          message: "Of course!",
          sentDate: "2023-10-11T19:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-65",
          message: "Be there in 10 mins.",
          sentDate: "2023-10-11T19:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-66",
          message: "See you soon!",
          sentDate: "2023-10-11T19:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    // User 12
    {
      userId: "12",
      name: "Jack Taylor",
      phoneNumber: "+2233445566",
      profilePic: "https://i.pravatar.cc/150?img=12",
      status: "Driving",
      messages: [
        {
          messageId: "msg-67",
          message: "Hey, are you driving?",
          sentDate: "2023-10-12T16:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-68",
          message: "Yes, I'll call you later.",
          sentDate: "2023-10-12T16:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-69",
          message: "Okay, drive safe!",
          sentDate: "2023-10-12T16:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-70",
          message: "Thanks!",
          sentDate: "2023-10-12T16:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-71",
          message: "Let me know when you're free.",
          sentDate: "2023-10-12T16:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-72",
          message: "Will do!",
          sentDate: "2023-10-12T16:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    // User 13
    {
      userId: "13",
      name: "Karen White",
      phoneNumber: "+6677889900",
      profilePic: "https://i.pravatar.cc/150?img=13",
      status: "At the gym",
      messages: [
        {
          messageId: "msg-73",
          message: "How's the workout going?",
          sentDate: "2023-10-13T17:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-74",
          message: "It's intense but good!",
          sentDate: "2023-10-13T17:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-75",
          message: "Keep it up!",
          sentDate: "2023-10-13T17:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-76",
          message: "Thanks!",
          sentDate: "2023-10-13T17:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-77",
          message: "Let's grab a smoothie after.",
          sentDate: "2023-10-13T17:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-78",
          message: "Sounds great!",
          sentDate: "2023-10-13T17:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    // User 14
    {
      userId: "14",
      name: "Leo Clark",
      phoneNumber: "+1122334455",
      profilePic: "https://i.pravatar.cc/150?img=14",
      status: "Traveling",
      messages: [
        {
          messageId: "msg-79",
          message: "How's the trip going?",
          sentDate: "2023-10-14T12:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-80",
          message: "Amazing! The views are stunning.",
          sentDate: "2023-10-14T12:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-81",
          message: "That's awesome!",
          sentDate: "2023-10-14T12:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-82",
          message: "Thanks!",
          sentDate: "2023-10-14T12:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-83",
          message: "Send some pictures!",
          sentDate: "2023-10-14T12:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-84",
          message: "Sure, will do.",
          sentDate: "2023-10-14T12:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    // User 15
    {
      userId: "15",
      name: "Mia Hall",
      phoneNumber: "+5566778899",
      profilePic: "https://i.pravatar.cc/150?img=15",
      status: "Reading",
      messages: [
        {
          messageId: "msg-85",
          message: "What book are you reading?",
          sentDate: "2023-10-15T14:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-86",
          message: "The Alchemist.",
          sentDate: "2023-10-15T14:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-87",
          message: "Oh, that's a great book!",
          sentDate: "2023-10-15T14:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-88",
          message: "Yes, I'm loving it so far.",
          sentDate: "2023-10-15T14:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-89",
          message: "Let me know how it ends.",
          sentDate: "2023-10-15T14:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-90",
          message: "Will do!",
          sentDate: "2023-10-15T14:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    {
      userId: "16",
      name: "Noah Young",
      phoneNumber: "+9988776655",
      profilePic: "https://i.pravatar.cc/150?img=16",
      status: "Working out",
      messages: [
        {
          messageId: "msg-91",
          message: "How's the workout going?",
          sentDate: "2023-10-16T18:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-92",
          message: "It's tough but rewarding!",
          sentDate: "2023-10-16T18:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-93",
          message: "Keep pushing!",
          sentDate: "2023-10-16T18:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-94",
          message: "Thanks for the motivation!",
          sentDate: "2023-10-16T18:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-95",
          message: "Let's hit the gym together next time.",
          sentDate: "2023-10-16T18:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-96",
          message: "Sounds like a plan!",
          sentDate: "2023-10-16T18:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    // User 17
    {
      userId: "17",
      name: "Olivia King",
      phoneNumber: "+1122334455",
      profilePic: "https://i.pravatar.cc/150?img=17",
      status: "Shopping",
      messages: [
        {
          messageId: "msg-97",
          message: "Found anything good?",
          sentDate: "2023-10-17T12:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-98",
          message: "Yes, got a great deal on shoes!",
          sentDate: "2023-10-17T12:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-99",
          message: "Nice! Send me a pic.",
          sentDate: "2023-10-17T12:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-100",
          message: "Sure, here you go.",
          sentDate: "2023-10-17T12:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-101",
          message: "Those look awesome!",
          sentDate: "2023-10-17T12:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-102",
          message: "Thanks!",
          sentDate: "2023-10-17T12:09:00",
          status: CONSTANT.STATUS_MESSAGE_UNREAD,
          isMessageSent: false,
        },
      ],
    },
    // User 18
    {
      userId: "18",
      name: "Paul Scott",
      phoneNumber: "+6677889900",
      profilePic: "https://i.pravatar.cc/150?img=18",
      status: "At home",
      messages: [
        {
          messageId: "msg-103",
          message: "What are you up to?",
          sentDate: "2023-10-18T20:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-104",
          message: "Just relaxing at home.",
          sentDate: "2023-10-18T20:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-105",
          message: "Wanna watch a movie?",
          sentDate: "2023-10-18T20:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-106",
          message: "Sure, what are we watching?",
          sentDate: "2023-10-18T20:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-107",
          message: "How about Inception?",
          sentDate: "2023-10-18T20:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-108",
          message: "Great choice!",
          sentDate: "2023-10-18T20:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
    // User 19
    {
      userId: "19",
      name: "Quinn Adams",
      phoneNumber: "+3344556677",
      profilePic: "https://i.pravatar.cc/150?img=19",
      status: "Busy",
      messages: [
        {
          messageId: "msg-109",
          message: "Can we talk later?",
          sentDate: "2023-10-19T09:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-110",
          message: "Yes, I'll call you at 5 PM.",
          sentDate: "2023-10-19T09:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-111",
          message: "Okay, see you then.",
          sentDate: "2023-10-19T09:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-112",
          message: "👍",
          sentDate: "2023-10-19T09:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-113",
          message: "Don't forget!",
          sentDate: "2023-10-19T09:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-114",
          message: "I won't!",
          sentDate: "2023-10-19T09:09:00",
          status: CONSTANT.STATUS_MESSAGE_UNREAD,
          isMessageSent: false,
        },
      ],
    },
    // User 20
    {
      userId: "20",
      name: "Rachel Green",
      phoneNumber: "+7788990011",
      profilePic: "https://i.pravatar.cc/150?img=20",
      status: "Available",
      messages: [
        {
          messageId: "msg-115",
          message: "Hey, what's up?",
          sentDate: "2023-10-20T10:00:00",
          status: "Read",
          isMessageSent: true,
        },
        {
          messageId: "msg-116",
          message: "Not much, just chilling.",
          sentDate: "2023-10-20T10:05:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-117",
          message: "Wanna hang out later?",
          sentDate: "2023-10-20T10:06:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-118",
          message: "Sure, let's meet at 7 PM.",
          sentDate: "2023-10-20T10:07:00",
          status: "Read",
          isMessageSent: false,
        },
        {
          messageId: "msg-119",
          message: "Perfect, see you then!",
          sentDate: "2023-10-20T10:08:00",
          status: "Delivered",
          isMessageSent: true,
        },
        {
          messageId: "msg-120",
          message: "👍",
          sentDate: "2023-10-20T10:09:00",
          status: "Not Delivered",
          isMessageSent: false,
        },
      ],
    },
  ],
};
